owner: keywordnew
repo: jinju-watchtower
user-agent: keywordnew

sites:
  - name: 한국 수자원 공사 (Korea Water Resources Corporation)
    url: https://www.kwater.or.kr/main.do?s_mid=1
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/water.png
  - name: 한국 전력 공사 (Korea Electric Power Corporation)
    url: https://home.kepco.co.kr/index.html
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/power-1.png
  - name: 에스케이텔레콤 (SK Telecom Co., Ltd.)
    url: https://www.sktelecom.com/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/communication.png
  - name: Gyeongsang National University Hospital
    url: https://www.gnuh.co.kr/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/hospital.png
  - name: 진주경찰서 (Jinju Police Station)
    url: http://www.gnpolice.go.kr/jj/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/emergency.png
  - name: 부산교통공사 (Busan Transportation Corporation, Jinju)
    url: http://www2.humetro.busan.kr/default/main.do
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/transportation-1.png
  - name: 주식회사 국민은행 (KB Bank)
    url: https://www.kbstar.com/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/payment.png


status-website:
  baseUrl: /jinju-watchtower
  name: 'Neighbourhood Cyber'
  logoUrl: https://nilspace.xyz/content/images/2023/05/favicon.png
  favicon: https://nilspace.xyz/content/images/2023/05/favicon.png
  introTitle: 'Jinju 🇰🇷 watchtower'
  introMessage: 'check if critical infrastructure may be down, or use GitHub ↗️ to "Watch" and get notified'
  navbar:
    - title: Status
      href: /jinju-watchtower
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Neighbourhoods
      href: https://github.com/$OWNER?tab=repositories&q=watchtower
      
i18n:
  footer: This Watchtower is part of [Project Watchtower](https://nilspace.xyz/project-watchtower/).
